# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Shiplifi"
application_url = "https://client-production-43d6.up.railway.app/shopify/install"
embedded = true
client_id = "1f4112e92d0bdb32baca637495ba34d6"

[auth]
redirect_urls = [
  "https://your-backend-service.up.railway.app/api/integrations/shopify/oauth/callback"
]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_orders,write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "https://your-backend-service.up.railway.app/api/webhooks/shopify/order-created"
  topics = [ "orders/create", "orders/updated", "orders/cancelled" ]

  [[webhooks.subscriptions]]
  uri = "https://your-backend-service.up.railway.app/api/webhooks/shopify/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://your-backend-service.up.railway.app/api/webhooks/shopify/app-uninstalled"
  topics = [ "app/uninstalled" ]
