UPDATE "shiplifi_b2b_additional_charges"
SET
  awb_charges = '100',
  cft_factor = '4500',
  minimum_chargeable_amount = '300',
  minimum_chargeable_weight = '20',
  minimum_chargeable_method = 'whichever_is_higher',
  free_storage_days = 4,
  demurrage_per_awb_day = '100',
  demurrage_per_kg_day = '1',
  demurrage_method = 'whichever_is_higher',
  public_holiday_pickup_charge = '0',
  fuel_surcharge_percentage = '0',
  green_tax = '0',
  oda_charges = '500',
  oda_per_kg_charge = '5',
  oda_method = 'whichever_is_higher',
  csd_delivery_charge = '500',
  time_specific_per_kg = '5',
  time_specific_per_awb = '500',
  time_specific_method = 'whichever_is_higher',
  mall_delivery_per_kg = '5',
  mall_delivery_per_awb = '500',
  mall_delivery_method = 'whichever_is_higher',
  delivery_reattempt_per_kg = '1',
  delivery_reattempt_per_awb = '100',
  delivery_reattempt_method = 'whichever_is_higher',
  handling_single_piece = '0',
  handling_below_100_kg = '0',
  handling_100_to_200_kg = '0',
  handling_above_200_kg = '0',
  insurance_charge = '0',
  cod_fixed_amount = '200',
  cod_percentage = '0.5',
  cod_method = 'whichever_is_higher',
  rov_fixed_amount = '150',
  rov_percentage = '0.25',
  rov_method = 'whichever_is_higher',
  custom_fields = COALESCE(custom_fields, '{}'::jsonb) || jsonb_build_object(
    'rovOwnerMinimum', 50,
    'rovCourierPercentage', 0.25,
    'rovCourierMinimum', 150,
    'packageHandling250To400PerKg', 1,
    'packageHandling400PlusPerKg', 3,
    'fodCharge', 200,
    'greenTaxPerKg', 0.4,
    'greenTaxMinimum', 80,
    'specialDeliveryPerKg', 5,
    'specialDeliveryMinimum', 500
  ),
  updated_at = NOW()
WHERE lower(COALESCE(service_provider, '')) = 'delhivery';
