CREATE TABLE IF NOT EXISTS international_shipments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id),
  shipment_number varchar(60) NOT NULL UNIQUE,
  pickup_id varchar(80),
  consignee_name varchar(180) NOT NULL,
  consignee_phone varchar(30) NOT NULL,
  consignee_alternate_phone varchar(30),
  consignee_email varchar(180),
  consignee_gstin varchar(30),
  address_line1 text NOT NULL,
  address_line2 text,
  landmark varchar(180),
  destination_pincode varchar(20) NOT NULL,
  destination_city varchar(120) NOT NULL,
  destination_state varchar(120) NOT NULL,
  destination_country varchar(80) NOT NULL,
  payment_method varchar(30) DEFAULT 'prepaid',
  rov varchar(50),
  item_type varchar(50),
  item_category varchar(80),
  shipping_mode varchar(50),
  products jsonb NOT NULL,
  packages jsonb NOT NULL,
  order_value numeric,
  applicable_weight numeric,
  invoice_number varchar(100),
  order_date timestamptz,
  eway_bill_no varchar(100),
  customer_reference_no varchar(120),
  seller_name varchar(180),
  status varchar(50) NOT NULL DEFAULT 'requested',
  awb_number varchar(100),
  booked_date timestamptz,
  admin_notes text,
  rate_quote jsonb,
  form_data jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS international_shipments_user_id_idx ON international_shipments(user_id);
CREATE INDEX IF NOT EXISTS international_shipments_status_idx ON international_shipments(status);
CREATE INDEX IF NOT EXISTS international_shipments_created_at_idx ON international_shipments(created_at DESC);
