import { sql } from 'drizzle-orm'
import { b2b_orders } from '../schema/b2bOrders'
import { b2c_orders } from '../schema/b2cOrders'
import { tracking_events } from '../schema/trackingEvents'

const orderSourceSelect = (integrationType: any, isExternalApi: any) => sql<string>`
  CASE
    WHEN lower(coalesce(${integrationType}, '')) = 'shopify' THEN 'shopify'
    WHEN lower(coalesce(${integrationType}, '')) = 'woocommerce' THEN 'woocommerce'
    WHEN coalesce(${isExternalApi}, false) THEN 'api'
    ELSE 'manual'
  END
`

// Keep list APIs pinned to stable columns. Newer optional DB columns can make
// broad select(*) queries fail when production migrations are not yet applied.
export const b2cOrderListSelect = {
  id: b2c_orders.id,
  user_id: b2c_orders.user_id,
  order_number: b2c_orders.order_number,
  order_date: b2c_orders.order_date,
  order_amount: b2c_orders.order_amount,
  order_id: b2c_orders.order_id,
  cod_charges: b2c_orders.cod_charges,
  invoice_number: b2c_orders.invoice_number,
  invoice_date: b2c_orders.invoice_date,
  invoice_amount: b2c_orders.invoice_amount,
  buyer_name: b2c_orders.buyer_name,
  buyer_phone: b2c_orders.buyer_phone,
  buyer_email: b2c_orders.buyer_email,
  address: b2c_orders.address,
  city: b2c_orders.city,
  state: b2c_orders.state,
  country: b2c_orders.country,
  pincode: b2c_orders.pincode,
  products: b2c_orders.products,
  weight: b2c_orders.weight,
  charged_weight: b2c_orders.charged_weight,
  length: b2c_orders.length,
  breadth: b2c_orders.breadth,
  height: b2c_orders.height,
  order_type: b2c_orders.order_type,
  prepaid_amount: b2c_orders.prepaid_amount,
  freight_charges: b2c_orders.freight_charges,
  shipping_charges: b2c_orders.shipping_charges,
  other_charges: sql<number>`0`,
  transaction_fee: b2c_orders.transaction_fee,
  gift_wrap: b2c_orders.gift_wrap,
  discount: b2c_orders.discount,
  edd: b2c_orders.edd,
  order_status: b2c_orders.order_status,
  courier_partner: b2c_orders.courier_partner,
  delivery_location: b2c_orders.delivery_location,
  delivery_message: b2c_orders.delivery_message,
  courier_id: b2c_orders.courier_id,
  shipping_mode: b2c_orders.shipping_mode,
  shipment_id: b2c_orders.shipment_id,
  provider_reference: b2c_orders.provider_reference,
  provider_request_id: b2c_orders.provider_request_id,
  provider_mode: b2c_orders.provider_mode,
  provider_service: b2c_orders.provider_service,
  provider_last_status: b2c_orders.provider_last_status,
  is_insurance: b2c_orders.is_insurance,
  label: b2c_orders.label,
  sort_code: b2c_orders.sort_code,
  invoice_link: b2c_orders.invoice_link,
  manifest: b2c_orders.manifest,
  manifest_error: sql<string | null>`NULL`,
  manifest_retry_count: sql<number>`0`,
  manifest_last_retry_at: sql<Date | null>`NULL`,
  awb_number: b2c_orders.awb_number,
  pickup_location_id: b2c_orders.pickup_location_id,
  pickup_details: b2c_orders.pickup_details,
  pickup_status: sql<string | null>`NULL`,
  pickup_error: sql<string | null>`NULL`,
  rto_details: b2c_orders.rto_details,
  is_rto_different: b2c_orders.is_rto_different,
  integration_type: b2c_orders.integration_type,
  is_external_api: b2c_orders.is_external_api,
  source: orderSourceSelect(b2c_orders.integration_type, b2c_orders.is_external_api),
  tags: b2c_orders.tags,
  created_at: b2c_orders.created_at,
  updated_at: b2c_orders.updated_at,
  last_tracking_update_at: sql<Date | null>`coalesce((
    select max(${tracking_events.created_at})
    from ${tracking_events}
    where ${tracking_events.order_id} = ${b2c_orders.id}
  ), ${b2c_orders.updated_at})`,
}

export const b2bOrderListSelect = {
  id: b2b_orders.id,
  user_id: b2b_orders.user_id,
  company_name: b2b_orders.company_name,
  company_gst: b2b_orders.company_gst,
  order_number: b2b_orders.order_number,
  cod_charges: b2b_orders.cod_charges,
  order_id: b2b_orders.order_id,
  order_date: b2b_orders.order_date,
  order_amount: b2b_orders.order_amount,
  integration_type: b2b_orders.integration_type,
  order_type: b2b_orders.order_type,
  prepaid_amount: b2b_orders.prepaid_amount,
  freight_charges: b2b_orders.freight_charges,
  shipping_charges: b2b_orders.shipping_charges,
  transaction_fee: b2b_orders.transaction_fee,
  discount: b2b_orders.discount,
  gift_wrap: b2b_orders.gift_wrap,
  order_status: b2b_orders.order_status,
  invoice_number: b2b_orders.invoice_number,
  invoice_date: b2b_orders.invoice_date,
  invoice_amount: b2b_orders.invoice_amount,
  buyer_name: b2b_orders.buyer_name,
  buyer_phone: b2b_orders.buyer_phone,
  buyer_email: b2b_orders.buyer_email,
  address: b2b_orders.address,
  city: b2b_orders.city,
  state: b2b_orders.state,
  country: b2b_orders.country,
  pincode: b2b_orders.pincode,
  label: b2b_orders.label,
  invoice_link: b2b_orders.invoice_link,
  manifest: b2b_orders.manifest,
  products: b2b_orders.products,
  packages: b2b_orders.packages,
  weight: b2b_orders.weight,
  charged_weight: b2b_orders.charged_weight,
  length: b2b_orders.length,
  breadth: b2b_orders.breadth,
  height: b2b_orders.height,
  courier_partner: b2b_orders.courier_partner,
  courier_id: b2b_orders.courier_id,
  awb_number: b2b_orders.awb_number,
  shipment_id: b2b_orders.shipment_id,
  provider_reference: b2b_orders.provider_reference,
  provider_request_id: b2b_orders.provider_request_id,
  provider_mode: b2b_orders.provider_mode,
  provider_service: b2b_orders.provider_service,
  provider_last_status: b2b_orders.provider_last_status,
  is_insurance: b2b_orders.is_insurance,
  delivery_location: b2b_orders.delivery_location,
  delivery_message: b2b_orders.delivery_message,
  pickup_location_id: b2b_orders.pickup_location_id,
  pickup_details: b2b_orders.pickup_details,
  rto_details: b2b_orders.rto_details,
  is_rto_different: b2b_orders.is_rto_different,
  is_external_api: b2b_orders.is_external_api,
  source: orderSourceSelect(b2b_orders.integration_type, b2b_orders.is_external_api),
  tags: b2b_orders.tags,
  created_at: b2b_orders.created_at,
  updated_at: b2b_orders.updated_at,
}
