[variables]
NODE_VERSION = "22.12.0"
NPM_CONFIG_CACHE = "/tmp/npm-cache"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --include=dev --cache /tmp/npm-cache --prefer-offline=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
