import { jsonb, numeric, pgTable, text, timestamp, uuid, varchar } from 'drizzle-orm/pg-core'
import { users } from './users'

export const internationalShipments = pgTable('international_shipments', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id').notNull().references(() => users.id),
  shipmentNumber: varchar('shipment_number', { length: 60 }).notNull().unique(),
  pickupId: varchar('pickup_id', { length: 80 }),
  consigneeName: varchar('consignee_name', { length: 180 }).notNull(),
  consigneePhone: varchar('consignee_phone', { length: 30 }).notNull(),
  consigneeAlternatePhone: varchar('consignee_alternate_phone', { length: 30 }),
  consigneeEmail: varchar('consignee_email', { length: 180 }),
  consigneeGstin: varchar('consignee_gstin', { length: 30 }),
  addressLine1: text('address_line1').notNull(),
  addressLine2: text('address_line2'),
  landmark: varchar('landmark', { length: 180 }),
  destinationPincode: varchar('destination_pincode', { length: 20 }).notNull(),
  destinationCity: varchar('destination_city', { length: 120 }).notNull(),
  destinationState: varchar('destination_state', { length: 120 }).notNull(),
  destinationCountry: varchar('destination_country', { length: 80 }).notNull(),
  paymentMethod: varchar('payment_method', { length: 30 }).default('prepaid'),
  rov: varchar('rov', { length: 50 }),
  itemType: varchar('item_type', { length: 50 }),
  itemCategory: varchar('item_category', { length: 80 }),
  shippingMode: varchar('shipping_mode', { length: 50 }),
  products: jsonb('products').notNull(),
  packages: jsonb('packages').notNull(),
  orderValue: numeric('order_value').$type<number>(),
  applicableWeight: numeric('applicable_weight').$type<number>(),
  invoiceNumber: varchar('invoice_number', { length: 100 }),
  orderDate: timestamp('order_date', { withTimezone: true }),
  ewayBillNo: varchar('eway_bill_no', { length: 100 }),
  customerReferenceNo: varchar('customer_reference_no', { length: 120 }),
  sellerName: varchar('seller_name', { length: 180 }),
  status: varchar('status', { length: 50 }).default('requested').notNull(),
  awbNumber: varchar('awb_number', { length: 100 }),
  bookedDate: timestamp('booked_date', { withTimezone: true }),
  adminNotes: text('admin_notes'),
  rateQuote: jsonb('rate_quote').$type<Record<string, unknown>>(),
  formData: jsonb('form_data').$type<Record<string, unknown>>(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
})
